//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class TahvilgirandeTbl
    {
        public TahvilgirandeTbl()
        {
            this.KhorujTbls = new HashSet<KhorujTbl>();
        }
    
        public long code { get; set; }
        public string name { get; set; }
        public string family { get; set; }
        public string address { get; set; }
        public string tell { get; set; }
    
        public virtual ICollection<KhorujTbl> KhorujTbls { get; set; }
    }
}
