//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class VorudTbl
    {
        public long vorudcode { get; set; }
        public Nullable<long> forushandecode { get; set; }
        public Nullable<long> kalacode { get; set; }
        public Nullable<int> tedad { get; set; }
        public string date { get; set; }
        public Nullable<System.DateTime> datereal { get; set; }
        public Nullable<long> motesadicode { get; set; }
    
        public virtual ForushandeTbl ForushandeTbl { get; set; }
        public virtual KalaTbl KalaTbl { get; set; }
        public virtual MotesadiTbl MotesadiTbl { get; set; }
    }
}
